POST  http://localhost:3333/videos
Content-Type: application/json

{
    "title":"video 02",
    "description":"video 02",
    "duration":120
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/81bcc8a9-fa8a-441e-90bd-d0df8600b993
Content-Type: application/json

{
    "title":"video 02",
    "description":"video 01",
    "duration":60
}

###

DELETE http://localhost:3333/videos/81bcc8a9-fa8a-441e-90bd-d0df8600b993